---
- hosts: localhost
  vars_files:
  - ../environment.yaml
  - ../global_defaults.yaml
  tasks:
  #- name: Disable K8S plugins
  #  shell:
  #    cmd: 'microk8s.disable {{ microK8s_addons }}'
  #  become: true
  - name: Uninstall Kubernetes
    shell:
      cmd: snap remove microk8s
    become: true



