---
- hosts: ggs
  vars_files:
  - ../environment.yaml
  - ../global_defaults.yaml
  tasks:
  - name: Create roles directory
    ansible.builtin.file:
      path: ../roles
      state: directory
  - name: Create subdirs
    ansible.builtin.file:
      path: '../roles/{{ item.name }}'
      state: directory
    with_items: '{{ roles }}'
  - name: Get Kubernetes role from git
    ansible.builtin.git:
      repo: '{{ item.git }}'
      dest: '../roles/{{ item.name }}'
      force: true
    with_items: '{{ roles }}'
  - name: Create resource folder
    ansible.builtin.file:
      path: '../resources'
      state: directory
  - name: Create webpage folder
    ansible.builtin.file:
      path: '../{{ resources }}/{{ webpage }}'
      state: directory
  - name: Get webpage
    ansible.builtin.git:
      repo: 'git@github.com:GeoGeekSuite/Startpage.git'
      dest: '../{{ resources }}/{{ webpage }}'
      force: true
    

    