---
- hosts: ggs
  vars_files:
  - ./environment.yaml
  - ./global_defaults.yaml
  tasks:
  - name: Smoke Test
    debug:
      msg: "Hi from {{ ansible_host }}"
    tags: ['never','smoketest']
  roles:
  #- { role: geogeeksuite.nfs,
  #    tags: nfs }
  - { role: geogeeksuite.credentials,
      tags: credentials }
  - { role: geogeeksuite.kubernetes,
      tags: kube }
  - { role: geogeeksuite.storage,
      tags: storage }
  - { role: geogeeksuite.geodatabase,
      tags: pg }
  - { role: geogeeksuite.pgadmin,
      tags: pga }
  - { role: geogeeksuite.webhoster,
      tags: webhoster }
  - { role: geogeeksuite.ingress,
      tags: ingress }
  - { role: geogeeksuite.ubuntu,
      tags: ubuntu }


