---
# tasks file for startpage
- name: Create dir for startpage
  file:
    path: '{{ startpage }}'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  become: true
- name: Render index
  template:
    src: index.j2.html
    dest: '{{ startpage }}/index.html'